# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_BD.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BD(object):
    def setupUi(self, BD):
        BD.setObjectName("BD")
        BD.resize(1149, 567)
        self.gridLayout = QtWidgets.QGridLayout(BD)
        self.gridLayout.setObjectName("gridLayout")
        self.toolBox = QtWidgets.QToolBox(BD)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.toolBox.setFont(font)
        self.toolBox.setStyleSheet("QToolBox QScrollArea>QWidget>QWidget\n"
"{\n"
"background:rgb(15, 23, 25);\n"
"color: rgba(255,102,56,255);\n"
"}\n"
"\n"
"QToolBox::tab {\n"
"background:rgba(41,51,48,255);\n"
"color: rgba(255,102,56,255);\n"
"border-radius:8px;  \n"
"padding: 35px 50px;\n"
"min-height:200px;\n"
"} \n"
"\n"
"QToolBox::tab:selected { \n"
"  background: rgba(255,102,56,255);\n"
"  color: rgba(41,51,48,255);\n"
"  border-radius:8px;  \n"
"padding: 35px 50px;\n"
"min-height:200px;\n"
"}")
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 1131, 409))
        self.page.setObjectName("page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableWidget = QtWidgets.QTableWidget(self.page)
        self.tableWidget.setStyleSheet("\n"
"QTableWidget {\n"
"    background:rgb(15, 23, 25);\n"
"    color: rgba(255,102,56,255);\n"
"    padding:20;\n"
"    border:none;\n"
"}\n"
"\n"
"QHeaderView::section\n"
"{\n"
"    background:rgb(15, 23, 25);\n"
"    color: rgba(255,102,56,255);\n"
"    border-style:none;\n"
"    font-family: \'Montserrat\', sans-serif;\n"
"}\n"
"\n"
"QHeaderView\n"
"{\n"
"    background:rgb(15, 23, 25);\n"
"    color: rgba(255,102,56,255);\n"
"\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    background:rgb(15, 23, 25);\n"
"    color: rgba(255,102,56,255);\n"
"    border-bottom:1px dashed white;\n"
"    font-family: \'Roboto\', sans-serif;\n"
"}\n"
"\n"
"\n"
"QTableWidget::item::selected {\n"
"    background: rgba(255,102,56,255);\n"
"    color: rgb(15, 23, 25);\n"
"    border-top: 1px solid #00FFFF;\n"
"    border-bottom: 1px solid #00FFFF;\n"
"}\n"
"\n"
"")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_3 = QtWidgets.QLabel(self.page)
        self.label_3.setStyleSheet("background:rgba(255,102,56,255);\n"
"color: rgba(41,51,48,255);")
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.page)
        self.label_4.setStyleSheet("background:rgba(255,102,56,255);\n"
"color: rgba(41,51,48,255);")
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 1, 1, 1)
        self.manufcturer_1 = QtWidgets.QLineEdit(self.page)
        self.manufcturer_1.setMinimumSize(QtCore.QSize(100, 20))
        self.manufcturer_1.setStyleSheet("background:rgba(41,51,48,255);\n"
"color: rgba(255,102,56,255);")
        self.manufcturer_1.setObjectName("manufcturer_1")
        self.gridLayout_3.addWidget(self.manufcturer_1, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.page)
        self.label_5.setStyleSheet("background:rgba(255,102,56,255);\n"
"color: rgba(41,51,48,255);")
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setStyleSheet("background:rgba(255,102,56,255);\n"
"color: rgba(41,51,48,255);")
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 4, 1, 1)
        self.delete_1 = QtWidgets.QPushButton(self.page)
        self.delete_1.setStyleSheet("QPushButton{\n"
"position: absolute;\n"
"top:50%;\n"
"background-color:rgba(41,51,48,255);\n"
"color: rgba(255,102,56,255);\n"
"border-radius:8px; \n"
"padding:10px;\n"
"min-height:30px; \n"
"min-width: 120px;\n"
"}\n"
"QPushButton:hover{\n"
"position: absolute;\n"
"top:50%;\n"
"background-color:rgba(255,102,56,255);\n"
"color: rgba(41,51,48,255);\n"
"border-radius:8px; \n"
"padding:10px;\n"
"min-height:30px; \n"
"min-width: 120px;\n"
"}")
        self.delete_1.setObjectName("delete_1")
        self.gridLayout_3.addWidget(self.delete_1, 0, 7, 1, 1)
        self.model_1 = QtWidgets.QLineEdit(self.page)
        self.model_1.setMinimumSize(QtCore.QSize(100, 20))
        self.model_1.setStyleSheet("background:rgba(41,51,48,255);\n"
"color: rgba(255,102,56,255);")
        self.model_1.setObjectName("model_1")
        self.gridLayout_3.addWidget(self.model_1, 1, 1, 1, 1)
        self.current_1 = QtWidgets.QLineEdit(self.page)
        self.current_1.setMinimumSize(QtCore.QSize(80, 20))
        self.current_1.setStyleSheet("background:rgba(41,51,48,255);\n"
"color: rgba(255,102,56,255);")
        self.current_1.setObjectName("current_1")
        self.gridLayout_3.addWidget(self.current_1, 1, 4, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.page)
        self.label_6.setStyleSheet("background:rgba(255,102,56,255);\n"
"color: rgba(41,51,48,255);")
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 6, 1, 1)
        self.speed_1 = QtWidgets.QLineEdit(self.page)
        self.speed_1.setMinimumSize(QtCore.QSize(100, 20))
        self.speed_1.setStyleSheet("background:rgba(41,51,48,255);\n"
"color: rgba(255,102,56,255);")
        self.speed_1.setObjectName("speed_1")
        self.gridLayout_3.addWidget(self.speed_1, 1, 5, 1, 1)
        self.moment_1 = QtWidgets.QLineEdit(self.page)
        self.moment_1.setMinimumSize(QtCore.QSize(100, 20))
        self.moment_1.setStyleSheet("background:rgba(41,51,48,255);\n"
"color: rgba(255,102,56,255);")
        self.moment_1.setObjectName("moment_1")
        self.gridLayout_3.addWidget(self.moment_1, 1, 6, 1, 1)
        self.label = QtWidgets.QLabel(self.page)
        self.label.setStyleSheet("background:rgba(255,102,56,255);\n"
"color: rgba(41,51,48,255);")
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 5, 1, 1)
        self.add_1 = QtWidgets.QPushButton(self.page)
        self.add_1.setStyleSheet("QPushButton{\n"
"position: absolute;\n"
"top:50%;\n"
"background-color:rgba(41,51,48,255);\n"
"color: rgba(255,102,56,255);\n"
"border-radius:8px; \n"
"padding:10px;\n"
"min-height:30px; \n"
"min-width: 120px;\n"
"}\n"
"QPushButton:hover{\n"
"position: absolute;\n"
"top:50%;\n"
"background-color:rgba(255,102,56,255);\n"
"color: rgba(41,51,48,255);\n"
"border-radius:8px; \n"
"padding:10px;\n"
"min-height:30px; \n"
"min-width: 120px;\n"
"}")
        self.add_1.setObjectName("add_1")
        self.gridLayout_3.addWidget(self.add_1, 1, 7, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.page)
        self.label_7.setStyleSheet("background:rgba(255,102,56,255);\n"
"color: rgba(41,51,48,255);")
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 2, 1, 1)
        self.type_1 = QtWidgets.QComboBox(self.page)
        self.type_1.setMinimumSize(QtCore.QSize(170, 20))
        self.type_1.setStyleSheet("background:rgba(41,51,48,255);\n"
"color: rgba(255,102,56,255);")
        self.type_1.setObjectName("type_1")
        self.type_1.addItem("")
        self.type_1.addItem("")
        self.type_1.addItem("")
        self.type_1.addItem("")
        self.gridLayout_3.addWidget(self.type_1, 1, 2, 1, 1)
        self.voltage_1 = QtWidgets.QComboBox(self.page)
        self.voltage_1.setMinimumSize(QtCore.QSize(80, 20))
        self.voltage_1.setStyleSheet("background:rgba(41,51,48,255);\n"
"color: rgba(255,102,56,255);")
        self.voltage_1.setObjectName("voltage_1")
        self.voltage_1.addItem("")
        self.voltage_1.addItem("")
        self.voltage_1.addItem("")
        self.gridLayout_3.addWidget(self.voltage_1, 1, 3, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 1131, 409))
        self.page_2.setObjectName("page_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.page_2)
        self.tableWidget_2.setStyleSheet("\n"
"QTableWidget {\n"
"    background:rgb(15, 23, 25);\n"
"    color: rgba(255,102,56,255);\n"
"    padding:20;\n"
"    border:none;\n"
"}\n"
"\n"
"QHeaderView::section\n"
"{\n"
"    background:rgb(15, 23, 25);\n"
"    color: rgba(255,102,56,255);\n"
"    border-style:none;\n"
"    font-family: \'Montserrat\', sans-serif;\n"
"}\n"
"\n"
"QHeaderView\n"
"{\n"
"    background:rgb(15, 23, 25);\n"
"    color: rgba(255,102,56,255);\n"
"\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    background:rgb(15, 23, 25);\n"
"    color: rgba(255,102,56,255);\n"
"    border-bottom:1px dashed white;\n"
"    font-family: \'Roboto\', sans-serif;\n"
"}\n"
"\n"
"\n"
"QTableWidget::item::selected {\n"
"    background: rgba(255,102,56,255);\n"
"    color: rgb(15, 23, 25);\n"
"    border-top: 1px solid #00FFFF;\n"
"    border-bottom: 1px solid #00FFFF;\n"
"}\n"
"\n"
"")
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(4)
        self.tableWidget_2.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        self.verticalLayout_4.addWidget(self.tableWidget_2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.delete_2 = QtWidgets.QPushButton(self.page_2)
        self.delete_2.setStyleSheet("QPushButton{\n"
"position: absolute;\n"
"top:50%;\n"
"background-color:rgba(41,51,48,255);\n"
"color: rgba(255,102,56,255);\n"
"border-radius:8px; \n"
"padding:10px;\n"
"min-height:30px; \n"
"min-width: 120px;\n"
"}\n"
"QPushButton:hover{\n"
"position: absolute;\n"
"top:50%;\n"
"background-color:rgba(255,102,56,255);\n"
"color: rgba(41,51,48,255);\n"
"border-radius:8px; \n"
"padding:10px;\n"
"min-height:30px; \n"
"min-width: 120px;\n"
"}")
        self.delete_2.setObjectName("delete_2")
        self.gridLayout_2.addWidget(self.delete_2, 0, 5, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.page_2)
        self.label_11.setStyleSheet("background:rgba(255,102,56,255);\n"
"color: rgba(41,51,48,255);")
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.page_2)
        self.label_9.setStyleSheet("background:rgba(255,102,56,255);\n"
"color: rgba(41,51,48,255);")
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 1, 1, 1)
        self.working_stroke_2 = QtWidgets.QLineEdit(self.page_2)
        self.working_stroke_2.setStyleSheet("background:rgba(41,51,48,255);\n"
"color: rgba(255,102,56,255);")
        self.working_stroke_2.setObjectName("working_stroke_2")
        self.gridLayout_2.addWidget(self.working_stroke_2, 1, 2, 1, 1)
        self.model_2 = QtWidgets.QLineEdit(self.page_2)
        self.model_2.setStyleSheet("background:rgba(41,51,48,255);\n"
"color: rgba(255,102,56,255);")
        self.model_2.setObjectName("model_2")
        self.gridLayout_2.addWidget(self.model_2, 1, 1, 1, 1)
        self.manufactorer_2 = QtWidgets.QLineEdit(self.page_2)
        self.manufactorer_2.setStyleSheet("background:rgba(41,51,48,255);\n"
"color: rgba(255,102,56,255);")
        self.manufactorer_2.setObjectName("manufactorer_2")
        self.gridLayout_2.addWidget(self.manufactorer_2, 1, 0, 1, 1)
        self.diametr_2 = QtWidgets.QLineEdit(self.page_2)
        self.diametr_2.setStyleSheet("background:rgba(41,51,48,255);\n"
"color: rgba(255,102,56,255);")
        self.diametr_2.setObjectName("diametr_2")
        self.gridLayout_2.addWidget(self.diametr_2, 1, 3, 1, 1)
        self.add_2 = QtWidgets.QPushButton(self.page_2)
        self.add_2.setStyleSheet("QPushButton{\n"
"position: absolute;\n"
"top:50%;\n"
"background-color:rgba(41,51,48,255);\n"
"color: rgba(255,102,56,255);\n"
"border-radius:8px; \n"
"padding:10px;\n"
"min-height:30px; \n"
"min-width: 120px;\n"
"}\n"
"QPushButton:hover{\n"
"position: absolute;\n"
"top:50%;\n"
"background-color:rgba(255,102,56,255);\n"
"color: rgba(41,51,48,255);\n"
"border-radius:8px; \n"
"padding:10px;\n"
"min-height:30px; \n"
"min-width: 120px;\n"
"}")
        self.add_2.setObjectName("add_2")
        self.gridLayout_2.addWidget(self.add_2, 1, 5, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.page_2)
        self.label_8.setStyleSheet("background:rgba(255,102,56,255);\n"
"color: rgba(41,51,48,255);")
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.page_2)
        self.label_10.setStyleSheet("background:rgba(255,102,56,255);\n"
"color: rgba(41,51,48,255);")
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.page_2)
        self.label_12.setStyleSheet("background:rgba(255,102,56,255);\n"
"color: rgba(41,51,48,255);")
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 0, 4, 1, 1)
        self.pressure_2 = QtWidgets.QLineEdit(self.page_2)
        self.pressure_2.setStyleSheet("background:rgba(41,51,48,255);\n"
"color: rgba(255,102,56,255);")
        self.pressure_2.setObjectName("pressure_2")
        self.gridLayout_2.addWidget(self.pressure_2, 1, 4, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_2)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.toolBox.addItem(self.page_2, "")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.page_3)
        self.tableWidget_3.setStyleSheet("\n"
"QTableWidget {\n"
"    background:rgb(15, 23, 25);\n"
"    color: rgba(255,102,56,255);\n"
"    padding:20;\n"
"    border:none;\n"
"}\n"
"\n"
"QHeaderView::section\n"
"{\n"
"    background:rgb(15, 23, 25);\n"
"    color: rgba(255,102,56,255);\n"
"    border-style:none;\n"
"    font-family: \'Montserrat\', sans-serif;\n"
"}\n"
"\n"
"QHeaderView\n"
"{\n"
"    background:rgb(15, 23, 25);\n"
"    color: rgba(255,102,56,255);\n"
"\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    background:rgb(15, 23, 25);\n"
"    color: rgba(255,102,56,255);\n"
"    border-bottom:1px dashed white;\n"
"    font-family: \'Roboto\', sans-serif;\n"
"}\n"
"\n"
"\n"
"QTableWidget::item::selected {\n"
"    background: rgba(255,102,56,255);\n"
"    color: rgb(15, 23, 25);\n"
"    border-top: 1px solid #00FFFF;\n"
"    border-bottom: 1px solid #00FFFF;\n"
"}\n"
"\n"
"")
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(3)
        self.tableWidget_3.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        self.verticalLayout.addWidget(self.tableWidget_3)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.add_3 = QtWidgets.QPushButton(self.page_3)
        self.add_3.setStyleSheet("QPushButton{\n"
"position: absolute;\n"
"top:50%;\n"
"background-color:rgba(41,51,48,255);\n"
"color: rgba(255,102,56,255);\n"
"border-radius:8px; \n"
"padding:10px;\n"
"min-height:30px; \n"
"min-width: 120px;\n"
"}\n"
"QPushButton:hover{\n"
"position: absolute;\n"
"top:50%;\n"
"background-color:rgba(255,102,56,255);\n"
"color: rgba(41,51,48,255);\n"
"border-radius:8px; \n"
"padding:10px;\n"
"min-height:30px; \n"
"min-width: 120px;\n"
"}")
        self.add_3.setObjectName("add_3")
        self.gridLayout_4.addWidget(self.add_3, 1, 3, 1, 1)
        self.delete_3 = QtWidgets.QPushButton(self.page_3)
        self.delete_3.setStyleSheet("QPushButton{\n"
"position: absolute;\n"
"top:50%;\n"
"background-color:rgba(41,51,48,255);\n"
"color: rgba(255,102,56,255);\n"
"border-radius:8px; \n"
"padding:10px;\n"
"min-height:30px; \n"
"min-width: 120px;\n"
"}\n"
"QPushButton:hover{\n"
"position: absolute;\n"
"top:50%;\n"
"background-color:rgba(255,102,56,255);\n"
"color: rgba(41,51,48,255);\n"
"border-radius:8px; \n"
"padding:10px;\n"
"min-height:30px; \n"
"min-width: 120px;\n"
"}")
        self.delete_3.setObjectName("delete_3")
        self.gridLayout_4.addWidget(self.delete_3, 0, 3, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.page_3)
        self.label_13.setStyleSheet("background:rgba(255,102,56,255);\n"
"color: rgba(41,51,48,255);")
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 0, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.page_3)
        self.label_14.setStyleSheet("background:rgba(255,102,56,255);\n"
"color: rgba(41,51,48,255);")
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.page_3)
        self.label_15.setStyleSheet("background:rgba(255,102,56,255);\n"
"color: rgba(41,51,48,255);")
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 0, 0, 1, 1)
        self.manufctorer_3 = QtWidgets.QLineEdit(self.page_3)
        self.manufctorer_3.setStyleSheet("background:rgba(41,51,48,255);\n"
"color: rgba(255,102,56,255);")
        self.manufctorer_3.setObjectName("manufctorer_3")
        self.gridLayout_4.addWidget(self.manufctorer_3, 1, 0, 1, 1)
        self.model_3 = QtWidgets.QLineEdit(self.page_3)
        self.model_3.setStyleSheet("background:rgba(41,51,48,255);\n"
"color: rgba(255,102,56,255);")
        self.model_3.setObjectName("model_3")
        self.gridLayout_4.addWidget(self.model_3, 1, 1, 1, 1)
        self.price_3 = QtWidgets.QLineEdit(self.page_3)
        self.price_3.setStyleSheet("background:rgba(41,51,48,255);\n"
"color: rgba(255,102,56,255);")
        self.price_3.setObjectName("price_3")
        self.gridLayout_4.addWidget(self.price_3, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_4)
        self.verticalLayout_6.addLayout(self.verticalLayout)
        self.toolBox.addItem(self.page_3, "")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.page_4)
        self.tableWidget_4.setStyleSheet("\n"
"QTableWidget {\n"
"    background:rgb(15, 23, 25);\n"
"    color: rgba(255,102,56,255);\n"
"    padding:20;\n"
"    border:none;\n"
"}\n"
"\n"
"QHeaderView::section\n"
"{\n"
"    background:rgb(15, 23, 25);\n"
"    color: rgba(255,102,56,255);\n"
"    border-style:none;\n"
"    font-family: \'Montserrat\', sans-serif;\n"
"}\n"
"\n"
"QHeaderView\n"
"{\n"
"    background:rgb(15, 23, 25);\n"
"    color: rgba(255,102,56,255);\n"
"\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    background:rgb(15, 23, 25);\n"
"    color: rgba(255,102,56,255);\n"
"    border-bottom:1px dashed white;\n"
"    font-family: \'Roboto\', sans-serif;\n"
"}\n"
"\n"
"\n"
"QTableWidget::item::selected {\n"
"    background: rgba(255,102,56,255);\n"
"    color: rgb(15, 23, 25);\n"
"    border-top: 1px solid #00FFFF;\n"
"    border-bottom: 1px solid #00FFFF;\n"
"}\n"
"\n"
"")
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(0)
        self.tableWidget_4.setRowCount(0)
        self.verticalLayout_7.addWidget(self.tableWidget_4)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.calculate_table_4 = QtWidgets.QPushButton(self.page_4)
        self.calculate_table_4.setStyleSheet("QPushButton{\n"
"position: absolute;\n"
"top:50%;\n"
"background-color:rgba(41,51,48,255);\n"
"color: rgba(255,102,56,255);\n"
"border-radius:8px; \n"
"padding:10px;\n"
"min-height:30px; \n"
"min-width: 120px;\n"
"}\n"
"QPushButton:hover{\n"
"position: absolute;\n"
"top:50%;\n"
"background-color:rgba(255,102,56,255);\n"
"color: rgba(41,51,48,255);\n"
"border-radius:8px; \n"
"padding:10px;\n"
"min-height:30px; \n"
"min-width: 120px;\n"
"}")
        self.calculate_table_4.setObjectName("calculate_table_4")
        self.gridLayout_5.addWidget(self.calculate_table_4, 0, 0, 1, 1)
        self.upload_table_4 = QtWidgets.QPushButton(self.page_4)
        self.upload_table_4.setStyleSheet("QPushButton{\n"
"position: absolute;\n"
"top:50%;\n"
"background-color:rgba(41,51,48,255);\n"
"color: rgba(255,102,56,255);\n"
"border-radius:8px; \n"
"padding:10px;\n"
"min-height:30px; \n"
"min-width: 120px;\n"
"}\n"
"QPushButton:hover{\n"
"position: absolute;\n"
"top:50%;\n"
"background-color:rgba(255,102,56,255);\n"
"color: rgba(41,51,48,255);\n"
"border-radius:8px; \n"
"padding:10px;\n"
"min-height:30px; \n"
"min-width: 120px;\n"
"}")
        self.upload_table_4.setObjectName("upload_table_4")
        self.gridLayout_5.addWidget(self.upload_table_4, 1, 0, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_5)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_16 = QtWidgets.QLabel(self.page_4)
        self.label_16.setStyleSheet("background:rgba(255,102,56,255);\n"
"color: rgba(41,51,48,255);\n"
"min-height:30px; \n"
"min-width: 120px;")
        self.label_16.setObjectName("label_16")
        self.gridLayout_6.addWidget(self.label_16, 1, 0, 1, 1)
        self.way_save_4 = QtWidgets.QLineEdit(self.page_4)
        self.way_save_4.setStyleSheet("background:rgba(41,51,48,255);\n"
"color: rgba(255,102,56,255);")
        self.way_save_4.setObjectName("way_save_4")
        self.gridLayout_6.addWidget(self.way_save_4, 2, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.page_4)
        self.label_17.setStyleSheet("background:rgba(255,102,56,255);\n"
"color: rgba(41,51,48,255);\n"
"min-height:30px; \n"
"min-width: 120px;")
        self.label_17.setObjectName("label_17")
        self.gridLayout_6.addWidget(self.label_17, 1, 1, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.page_4)
        self.comboBox_3.setAcceptDrops(False)
        self.comboBox_3.setAutoFillBackground(False)
        self.comboBox_3.setStyleSheet("background:rgba(41,51,48,255);\n"
"color: rgba(255,102,56,255);")
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.gridLayout_6.addWidget(self.comboBox_3, 2, 1, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_6)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.toolBox.addItem(self.page_4, "")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.page_5)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.tableWidget_5 = QtWidgets.QTableWidget(self.page_5)
        self.tableWidget_5.setStyleSheet("\n"
"QTableWidget {\n"
"    background:rgb(15, 23, 25);\n"
"    color: rgba(255,102,56,255);\n"
"    padding:20;\n"
"    border:none;\n"
"}\n"
"\n"
"QHeaderView::section\n"
"{\n"
"    background:rgb(15, 23, 25);\n"
"    color: rgba(255,102,56,255);\n"
"    border-style:none;\n"
"    font-family: \'Montserrat\', sans-serif;\n"
"}\n"
"\n"
"QHeaderView\n"
"{\n"
"    background:rgb(15, 23, 25);\n"
"    color: rgba(255,102,56,255);\n"
"\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    background:rgb(15, 23, 25);\n"
"    color: rgba(255,102,56,255);\n"
"    border-bottom:1px dashed white;\n"
"    font-family: \'Roboto\', sans-serif;\n"
"}\n"
"\n"
"\n"
"QTableWidget::item::selected {\n"
"    background: rgba(255,102,56,255);\n"
"    color: rgb(15, 23, 25);\n"
"    border-top: 1px solid #00FFFF;\n"
"    border-bottom: 1px solid #00FFFF;\n"
"}\n"
"\n"
"")
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.setColumnCount(0)
        self.tableWidget_5.setRowCount(0)
        self.verticalLayout_10.addWidget(self.tableWidget_5)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.way_upload_5 = QtWidgets.QLineEdit(self.page_5)
        self.way_upload_5.setStyleSheet("background:rgba(41,51,48,255);\n"
"color: rgba(255,102,56,255);")
        self.way_upload_5.setObjectName("way_upload_5")
        self.gridLayout_7.addWidget(self.way_upload_5, 1, 2, 1, 1)
        self.min_string_5 = QtWidgets.QSpinBox(self.page_5)
        self.min_string_5.setStyleSheet("background:rgba(41,51,48,255);\n"
"color: rgba(255,102,56,255);")
        self.min_string_5.setMaximum(10000)
        self.min_string_5.setObjectName("min_string_5")
        self.gridLayout_7.addWidget(self.min_string_5, 1, 4, 1, 1)
        self.open_table_5 = QtWidgets.QPushButton(self.page_5)
        self.open_table_5.setStyleSheet("QPushButton{\n"
"position: absolute;\n"
"top:50%;\n"
"background-color:rgba(41,51,48,255);\n"
"color: rgba(255,102,56,255);\n"
"border-radius:8px; \n"
"padding:10px;\n"
"min-height:30px; \n"
"min-width: 120px;\n"
"}\n"
"QPushButton:hover{\n"
"position: absolute;\n"
"top:50%;\n"
"background-color:rgba(255,102,56,255);\n"
"color: rgba(41,51,48,255);\n"
"border-radius:8px; \n"
"padding:10px;\n"
"min-height:30px; \n"
"min-width: 120px;\n"
"}")
        self.open_table_5.setObjectName("open_table_5")
        self.gridLayout_7.addWidget(self.open_table_5, 0, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.page_5)
        self.label_21.setStyleSheet("background:rgba(255,102,56,255);\n"
"color: rgba(41,51,48,255);\n"
"min-height:30px; \n"
"min-width: 120px;")
        self.label_21.setObjectName("label_21")
        self.gridLayout_7.addWidget(self.label_21, 0, 4, 1, 1)
        self.add_table_5 = QtWidgets.QPushButton(self.page_5)
        self.add_table_5.setStyleSheet("QPushButton{\n"
"position: absolute;\n"
"top:50%;\n"
"background-color:rgba(41,51,48,255);\n"
"color: rgba(255,102,56,255);\n"
"border-radius:8px; \n"
"padding:10px;\n"
"min-height:30px; \n"
"min-width: 120px;\n"
"}\n"
"QPushButton:hover{\n"
"position: absolute;\n"
"top:50%;\n"
"background-color:rgba(255,102,56,255);\n"
"color: rgba(41,51,48,255);\n"
"border-radius:8px; \n"
"padding:10px;\n"
"min-height:30px; \n"
"min-width: 120px;\n"
"}")
        self.add_table_5.setObjectName("add_table_5")
        self.gridLayout_7.addWidget(self.add_table_5, 1, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.page_5)
        self.label_18.setStyleSheet("background:rgba(255,102,56,255);\n"
"color: rgba(41,51,48,255);\n"
"min-height:30px; \n"
"min-width: 120px;")
        self.label_18.setObjectName("label_18")
        self.gridLayout_7.addWidget(self.label_18, 0, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.page_5)
        self.label_19.setStyleSheet("background:rgba(255,102,56,255);\n"
"color: rgba(41,51,48,255);\n"
"min-height:30px; \n"
"min-width: 120px;")
        self.label_19.setObjectName("label_19")
        self.gridLayout_7.addWidget(self.label_19, 0, 2, 1, 1)
        self.comboBox_5 = QtWidgets.QComboBox(self.page_5)
        self.comboBox_5.setStyleSheet("background:rgba(41,51,48,255);\n"
"color: rgba(255,102,56,255);")
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.gridLayout_7.addWidget(self.comboBox_5, 1, 3, 1, 1)
        self.spinBox_2 = QtWidgets.QSpinBox(self.page_5)
        self.spinBox_2.setStyleSheet("background:rgba(41,51,48,255);\n"
"color: rgba(255,102,56,255);")
        self.spinBox_2.setMaximum(10000)
        self.spinBox_2.setProperty("value", 1000)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout_7.addWidget(self.spinBox_2, 1, 5, 1, 1)
        self.type_5 = QtWidgets.QComboBox(self.page_5)
        self.type_5.setStyleSheet("background:rgba(41,51,48,255);\n"
"color: rgba(255,102,56,255);")
        self.type_5.setObjectName("type_5")
        self.type_5.addItem("")
        self.type_5.addItem("")
        self.type_5.addItem("")
        self.type_5.addItem("")
        self.gridLayout_7.addWidget(self.type_5, 1, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.page_5)
        self.label_22.setStyleSheet("background:rgba(255,102,56,255);\n"
"color: rgba(41,51,48,255);\n"
"min-height:30px; \n"
"min-width: 120px;")
        self.label_22.setObjectName("label_22")
        self.gridLayout_7.addWidget(self.label_22, 0, 5, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.page_5)
        self.label_20.setStyleSheet("background:rgba(255,102,56,255);\n"
"color: rgba(41,51,48,255);\n"
"min-height:30px; \n"
"min-width: 120px;")
        self.label_20.setObjectName("label_20")
        self.gridLayout_7.addWidget(self.label_20, 0, 3, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.page_5)
        self.checkBox.setStyleSheet("background:rgba(41,51,48,255);\n"
"color: rgba(255,102,56,255);")
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_7.addWidget(self.checkBox, 0, 6, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_7)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        self.toolBox.addItem(self.page_5, "")
        self.gridLayout.addWidget(self.toolBox, 0, 0, 1, 1)

        self.retranslateUi(BD)
        self.toolBox.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(BD)

    def retranslateUi(self, BD):
        _translate = QtCore.QCoreApplication.translate
        BD.setWindowTitle(_translate("BD", "Form"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("BD", "Двигатель 1"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("BD", "Производитель"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("BD", "Модель"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("BD", "Тип двигателя"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("BD", "Напряжение"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("BD", "Ток"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("BD", "Момент"))
        self.label_3.setText(_translate("BD", "Напряжение. В"))
        self.label_4.setText(_translate("BD", "Модель"))
        self.manufcturer_1.setText(_translate("BD", "PL"))
        self.label_5.setText(_translate("BD", "Производитель "))
        self.label_2.setText(_translate("BD", "Ток. А"))
        self.delete_1.setText(_translate("BD", "Удалить строку"))
        self.model_1.setText(_translate("BD", "PL42BLF80-240"))
        self.label_6.setText(_translate("BD", "Момент. Нм"))
        self.label.setText(_translate("BD", "Скорость\n"
"Вращения. об/мин"))
        self.add_1.setText(_translate("BD", "Добавить строку"))
        self.label_7.setText(_translate("BD", "Тип двигателя"))
        self.type_1.setItemText(0, _translate("BD", "Шаговый двигатель"))
        self.type_1.setItemText(1, _translate("BD", "Серводвигатель"))
        self.type_1.setItemText(2, _translate("BD", "Бесколлекторный двигатель"))
        self.type_1.setItemText(3, _translate("BD", "Двигатель постоянного тока"))
        self.voltage_1.setItemText(0, _translate("BD", "12В"))
        self.voltage_1.setItemText(1, _translate("BD", "24В"))
        self.voltage_1.setItemText(2, _translate("BD", "36В"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("BD", "Двигатели"))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("BD", "Пневмоцилиндр 1"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("BD", "Производитель"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("BD", "Модель"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("BD", "Рабочий ход"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("BD", "Давление"))
        self.delete_2.setText(_translate("BD", "Удалить строку"))
        self.label_11.setText(_translate("BD", "Диаметр, мм"))
        self.label_9.setText(_translate("BD", "Модель"))
        self.add_2.setText(_translate("BD", "Добавить строку"))
        self.label_8.setText(_translate("BD", "Производитель"))
        self.label_10.setText(_translate("BD", "Рабочий ход, мм"))
        self.label_12.setText(_translate("BD", "Давление, МПа"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("BD", "Пневмоцилиндры"))
        item = self.tableWidget_3.verticalHeaderItem(0)
        item.setText(_translate("BD", "Компонент 1"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("BD", "Производитель"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("BD", "Модель"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("BD", "Стоимость"))
        self.add_3.setText(_translate("BD", "Добавить строку"))
        self.delete_3.setText(_translate("BD", "Удалить строку"))
        self.label_13.setText(_translate("BD", "Стоимость, руб"))
        self.label_14.setText(_translate("BD", "Модель"))
        self.label_15.setText(_translate("BD", "Производитель "))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("BD", "Стоимость оборудования"))
        self.calculate_table_4.setText(_translate("BD", "Рассчитать итоговую таблицу из характеристик робота"))
        self.upload_table_4.setText(_translate("BD", "Выгрузить итоговую таблицу"))
        self.label_16.setText(_translate("BD", "Путь сохранения"))
        self.label_17.setText(_translate("BD", "Формат файла"))
        self.comboBox_3.setItemText(0, _translate("BD", ".xlsx"))
        self.comboBox_3.setItemText(1, _translate("BD", ".csv"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), _translate("BD", "Итоговая конфигурация"))
        self.open_table_5.setText(_translate("BD", "Открыть выбранные строки"))
        self.label_21.setText(_translate("BD", "Начальное значени"))
        self.add_table_5.setText(_translate("BD", "Вставить строки в файл"))
        self.label_18.setText(_translate("BD", "Тип продукции"))
        self.label_19.setText(_translate("BD", "Путь содержащий файл"))
        self.comboBox_5.setItemText(0, _translate("BD", ".xlsx"))
        self.comboBox_5.setItemText(1, _translate("BD", ".csv"))
        self.type_5.setItemText(0, _translate("BD", "Двигатель"))
        self.type_5.setItemText(1, _translate("BD", "Пневмоцидиндр"))
        self.type_5.setItemText(2, _translate("BD", "Стоимость компонента"))
        self.type_5.setItemText(3, _translate("BD", "Другое"))
        self.label_22.setText(_translate("BD", "Конечное значение"))
        self.label_20.setText(_translate("BD", "Расширение файла"))
        self.checkBox.setText(_translate("BD", "Весь файл?"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_5), _translate("BD", "Вставить строки из файла"))
